/**
 * This file was automatically generated by the Mule Development Kit
 */
#set($D='$')
#set($moduleNameLower = "${muleModuleName.toLowerCase()}")
package ${muleModulePackage};

import org.mule.devkit.annotations.Module;
import org.mule.devkit.annotations.Configurable;
import org.mule.devkit.annotations.Processor;

@Module(name="${moduleNameLower}")
public class ${muleModuleName}Module
{
    @Configurable
    private String myProperty;

    public void setMyProperty(String myProperty)
    {
        this.myProperty = myProperty;
    }

    @Processor
    public String doSomething(String content)
    {
        /*
         * MESSAGE PROCESSOR CODE GOES HERE
         */

        return content;
    }
}
