/**
 * This file was automatically generated by the Mule Development Kit
 */
#set($D='$')
#set($moduleNameLower = "${muleModuleName.toLowerCase()}")
#set($moduleGroupIdPath = $groupId.replace(".", "/"))
package ${package};

import org.mule.api.annotations.ExpressionLanguage;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.ExpressionEvaluator;

import org.mule.api.annotations.param.Payload;

/**
 * Expression Language
 *
 * @author MuleSoft, Inc.
 */
@ExpressionLanguage(name="${moduleNameLower}")
public class ${muleModuleName}ExpressionLanguage
{
    /**
     * Evaluator
     *
     * {@sample.xml ../../../doc/${muleModuleName}-expression-language.xml.sample ${moduleNameLower}:evaluate}
     *
     * @return An object representing the expression evaluated
     */
    @ExpressionEvaluator
    public Object evaluate(String expression, @Payload Object payload) {

        return "Evaluated Expression";
    }
}
