/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 10:40:36 AM CDT 
//


package org.mule.devkit.model.studio;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EndpointType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="EndpointType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mulesoft.org/schema/mule/tooling.attributes}AbstractElementType">
 *       &lt;attribute name="supportsInbound" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="supportsOutbound" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="inboundLocalName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="defaultMep" type="{http://www.mulesoft.org/schema/mule/tooling.attributes}defaultMepType" />
 *       &lt;attribute name="outboundLocalName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EndpointType")
public class EndpointType
        extends AbstractElementType {

    @XmlAttribute(name = "supportsInbound")
    protected Boolean supportsInbound;
    @XmlAttribute(name = "supportsOutbound")
    protected Boolean supportsOutbound;
    @XmlAttribute(name = "inboundLocalName")
    protected String inboundLocalName;
    @XmlAttribute(name = "defaultMep")
    protected DefaultMepType defaultMep;
    @XmlAttribute(name = "outboundLocalName")
    protected String outboundLocalName;

    /**
     * Gets the value of the supportsInbound property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public Boolean isSupportsInbound() {
        return supportsInbound;
    }

    /**
     * Sets the value of the supportsInbound property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setSupportsInbound(Boolean value) {
        this.supportsInbound = value;
    }

    /**
     * Gets the value of the supportsOutbound property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public Boolean isSupportsOutbound() {
        return supportsOutbound;
    }

    /**
     * Sets the value of the supportsOutbound property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setSupportsOutbound(Boolean value) {
        this.supportsOutbound = value;
    }

    /**
     * Gets the value of the inboundLocalName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getInboundLocalName() {
        return inboundLocalName;
    }

    /**
     * Sets the value of the inboundLocalName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInboundLocalName(String value) {
        this.inboundLocalName = value;
    }

    /**
     * Gets the value of the defaultMep property.
     *
     * @return possible object is
     *         {@link DefaultMepType }
     */
    public DefaultMepType getDefaultMep() {
        return defaultMep;
    }

    /**
     * Sets the value of the defaultMep property.
     *
     * @param value allowed object is
     *              {@link DefaultMepType }
     */
    public void setDefaultMep(DefaultMepType value) {
        this.defaultMep = value;
    }

    /**
     * Gets the value of the outboundLocalName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getOutboundLocalName() {
        return outboundLocalName;
    }

    /**
     * Sets the value of the outboundLocalName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOutboundLocalName(String value) {
        this.outboundLocalName = value;
    }

}
