/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 10:40:36 AM CDT 
//
package org.mule.devkit.model.studio;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ModeType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ModeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mulesoft.org/schema/mule/tooling.attributes}AttributeType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="mode" type="{http://www.mulesoft.org/schema/mule/tooling.attributes}ModeElementType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="changesVisibility" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModeType", propOrder = {
        "mode"
})
public class ModeType
        extends AttributeType {

    @XmlElement(required = true)
    protected List<ModeElementType> mode;
    @XmlAttribute(name = "changesVisibility")
    protected Boolean changesVisibility;

    /**
     * Gets the value of the mode property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mode property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMode().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ModeElementType }
     */
    public List<ModeElementType> getMode() {
        if (mode == null) {
            mode = new ArrayList<ModeElementType>();
        }
        return this.mode;
    }

    /**
     * Gets the value of the changesVisibility property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public Boolean isChangesVisibility() {
        return changesVisibility;
    }

    /**
     * Sets the value of the changesVisibility property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setChangesVisibility(Boolean value) {
        this.changesVisibility = value;
    }

}
