/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 10:40:36 AM CDT 
//


package org.mule.devkit.model.studio;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for NamespaceType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="NamespaceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;element ref="{http://www.mulesoft.org/schema/mule/tooling.attributes}connector"/>
 *           &lt;element ref="{http://www.mulesoft.org/schema/mule/tooling.attributes}endpoint"/>
 *           &lt;element ref="{http://www.mulesoft.org/schema/mule/tooling.attributes}global"/>
 *           &lt;element ref="{http://www.mulesoft.org/schema/mule/tooling.attributes}pattern"/>
 *           &lt;element ref="{http://www.mulesoft.org/schema/mule/tooling.attributes}scope"/>
 *           &lt;element name="global-filter" type="{http://www.mulesoft.org/schema/mule/tooling.attributes}GlobalType"/>
 *           &lt;element name="global-transformer" type="{http://www.mulesoft.org/schema/mule/tooling.attributes}GlobalType"/>
 *           &lt;element name="global-cloud-connector" type="{http://www.mulesoft.org/schema/mule/tooling.attributes}GlobalType"/>
 *           &lt;element name="global-endpoint" type="{http://www.mulesoft.org/schema/mule/tooling.attributes}GlobalType"/>
 *           &lt;element name="filter" type="{http://www.mulesoft.org/schema/mule/tooling.attributes}PatternType"/>
 *           &lt;element name="transformer" type="{http://www.mulesoft.org/schema/mule/tooling.attributes}PatternType"/>
 *           &lt;element name="component" type="{http://www.mulesoft.org/schema/mule/tooling.attributes}PatternType"/>
 *           &lt;element name="flow" type="{http://www.mulesoft.org/schema/mule/tooling.attributes}PatternType"/>
 *           &lt;element name="router" type="{http://www.mulesoft.org/schema/mule/tooling.attributes}PatternType"/>
 *           &lt;element name="cloud-connector" type="{http://www.mulesoft.org/schema/mule/tooling.attributes}PatternType"/>
 *           &lt;element ref="{http://www.mulesoft.org/schema/mule/tooling.attributes}nested"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="prefix" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NamespaceType", propOrder = {
        "connectorOrEndpointOrGlobal"
})
@XmlRootElement(name = "namespace")
public class NamespaceType {

    @XmlElementRefs({
            @XmlElementRef(name = "global-transformer", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "pattern", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "nested", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "endpoint", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "global-cloud-connector", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "transformer", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "connector", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "component", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "scope", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "filter", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "global", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "flow", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "router", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "global-endpoint", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "cloud-connector", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class),
            @XmlElementRef(name = "global-filter", namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", type = JAXBElement.class)
    })
    protected List<JAXBElement<? extends AbstractElementType>> connectorOrEndpointOrGlobal;
    @XmlAttribute(name = "url")
    protected String url;
    @XmlAttribute(name = "prefix", required = true)
    protected String prefix;
    @XmlAttribute(name = "description")
    protected String description;

    /**
     * Gets the value of the connectorOrEndpointOrGlobal property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connectorOrEndpointOrGlobal property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectorOrEndpointOrGlobal().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link GlobalType }{@code >}
     * {@link JAXBElement }{@code <}{@link PatternType }{@code >}
     * {@link JAXBElement }{@code <}{@link NestedElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link EndpointType }{@code >}
     * {@link JAXBElement }{@code <}{@link GlobalType }{@code >}
     * {@link JAXBElement }{@code <}{@link PatternType }{@code >}
     * {@link JAXBElement }{@code <}{@link ConnectorType }{@code >}
     * {@link JAXBElement }{@code <}{@link PatternType }{@code >}
     * {@link JAXBElement }{@code <}{@link ScopeType }{@code >}
     * {@link JAXBElement }{@code <}{@link PatternType }{@code >}
     * {@link JAXBElement }{@code <}{@link GlobalType }{@code >}
     * {@link JAXBElement }{@code <}{@link PatternType }{@code >}
     * {@link JAXBElement }{@code <}{@link PatternType }{@code >}
     * {@link JAXBElement }{@code <}{@link GlobalType }{@code >}
     * {@link JAXBElement }{@code <}{@link PatternType }{@code >}
     * {@link JAXBElement }{@code <}{@link GlobalType }{@code >}
     */
    public List<JAXBElement<? extends AbstractElementType>> getConnectorOrEndpointOrGlobal() {
        if (connectorOrEndpointOrGlobal == null) {
            connectorOrEndpointOrGlobal = new ArrayList<JAXBElement<? extends AbstractElementType>>();
        }
        return this.connectorOrEndpointOrGlobal;
    }

    /**
     * Gets the value of the url property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the prefix property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
