/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 10:40:36 AM CDT 
//


package org.mule.devkit.model.studio;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.mule.devkit.model.studio package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Group_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "group");
    private final static QName _Namespace_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "namespace");
    private final static QName _Endpoint_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "endpoint");
    private final static QName _Connector_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "connector");
    private final static QName _Attributes_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "attributes");
    private final static QName _AttributeCategory_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "attribute-category");
    private final static QName _Pattern_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "pattern");
    private final static QName _Nested_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "nested");
    private final static QName _Global_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "global");
    private final static QName _Scope_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "scope");
    private final static QName _GroupModeSwitch_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "modeSwitch");
    private final static QName _GroupRegexp_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "regexp");
    private final static QName _GroupTransientBoolean_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "transientBoolean");
    private final static QName _GroupEncoding_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "encoding");
    private final static QName _GroupPath_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "path");
    private final static QName _GroupBoolean_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "boolean");
    private final static QName _GroupChildElement_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "childElement");
    private final static QName _GroupString_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "string");
    private final static QName _GroupName_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "name");
    private final static QName _GroupFile_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "file");
    private final static QName _GroupPassword_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "password");
    private final static QName _GroupLong_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "long");
    private final static QName _GroupUrl_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "url");
    private final static QName _GroupGlobalRef_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "globalRef");
    private final static QName _GroupEnum_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "enum");
    private final static QName _GroupList_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "list");
    private final static QName _GroupFlowRef_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "flowRef");
    private final static QName _GroupInteger_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "integer");
    private final static QName _GroupClassname_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "classname");
    private final static QName _GroupExpression_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "expression");
    private final static QName _GroupText_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "text");
    private final static QName _NamespaceTypeCloudConnector_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "cloud-connector");
    private final static QName _NamespaceTypeFilter_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "filter");
    private final static QName _NamespaceTypeTransformer_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "transformer");
    private final static QName _NamespaceTypeGlobalCloudConnector_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "global-cloud-connector");
    private final static QName _NamespaceTypeFlow_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "flow");
    private final static QName _NamespaceTypeGlobalTransformer_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "global-transformer");
    private final static QName _NamespaceTypeComponent_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "component");
    private final static QName _NamespaceTypeGlobalEndpoint_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "global-endpoint");
    private final static QName _NamespaceTypeRouter_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "router");
    private final static QName _NamespaceTypeGlobalFilter_QNAME = new QName("http://www.mulesoft.org/schema/mule/tooling.attributes", "global-filter");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mule.devkit.model.studio
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LongType }
     */
    public LongType createLongType() {
        return new LongType();
    }

    /**
     * Create an instance of {@link EndpointType }
     */
    public EndpointType createEndpointType() {
        return new EndpointType();
    }

    /**
     * Create an instance of {@link ModeElementType }
     */
    public ModeElementType createModeElementType() {
        return new ModeElementType();
    }

    /**
     * Create an instance of {@link NestedElementReference }
     */
    public NestedElementReference createNestedElementReference() {
        return new NestedElementReference();
    }

    /**
     * Create an instance of {@link Group }
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link EncodingType }
     */
    public EncodingType createEncodingType() {
        return new EncodingType();
    }

    /**
     * Create an instance of {@link NamespaceType }
     */
    public NamespaceType createNamespaceType() {
        return new NamespaceType();
    }

    /**
     * Create an instance of {@link ExpressionAttributeType }
     */
    public ExpressionAttributeType createExpressionAttributeType() {
        return new ExpressionAttributeType();
    }

    /**
     * Create an instance of {@link ConnectorType }
     */
    public ConnectorType createConnectorType() {
        return new ConnectorType();
    }

    /**
     * Create an instance of {@link ScopeType }
     */
    public ScopeType createScopeType() {
        return new ScopeType();
    }

    /**
     * Create an instance of {@link AlternativesType.Alternative }
     */
    public AlternativesType.Alternative createAlternativesTypeAlternative() {
        return new AlternativesType.Alternative();
    }

    /**
     * Create an instance of {@link NewType }
     */
    public NewType createNewType() {
        return new NewType();
    }

    /**
     * Create an instance of {@link Attributes }
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link Module }
     */
    public Module createModule() {
        return new Module();
    }

    /**
     * Create an instance of {@link IntegerType }
     */
    public IntegerType createIntegerType() {
        return new IntegerType();
    }

    /**
     * Create an instance of {@link NestedElementType }
     */
    public NestedElementType createNestedElementType() {
        return new NestedElementType();
    }

    /**
     * Create an instance of {@link AttributeCategory }
     */
    public AttributeCategory createAttributeCategory() {
        return new AttributeCategory();
    }

    /**
     * Create an instance of {@link Booleantype }
     */
    public Booleantype createBooleantype() {
        return new Booleantype();
    }

    /**
     * Create an instance of {@link TextType }
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link FixedAttributeType }
     */
    public FixedAttributeType createFixedAttributeType() {
        return new FixedAttributeType();
    }

    /**
     * Create an instance of {@link AbstractElementType }
     */
    public AbstractElementType createAbstractElementType() {
        return new AbstractElementType();
    }

    /**
     * Create an instance of {@link ClassType }
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link EnumElement }
     */
    public EnumElement createEnumElement() {
        return new EnumElement();
    }

    /**
     * Create an instance of {@link PatternType }
     */
    public PatternType createPatternType() {
        return new PatternType();
    }

    /**
     * Create an instance of {@link AlternativesType }
     */
    public AlternativesType createAlternativesType() {
        return new AlternativesType();
    }

    /**
     * Create an instance of {@link StringAttributeType }
     */
    public StringAttributeType createStringAttributeType() {
        return new StringAttributeType();
    }

    /**
     * Create an instance of {@link GlobalType }
     */
    public GlobalType createGlobalType() {
        return new GlobalType();
    }

    /**
     * Create an instance of {@link ModeType }
     */
    public ModeType createModeType() {
        return new ModeType();
    }

    /**
     * Create an instance of {@link AlwaysAdd }
     */
    public AlwaysAdd createAlwaysAdd() {
        return new AlwaysAdd();
    }

    /**
     * Create an instance of {@link EnumType }
     */
    public EnumType createEnumType() {
        return new EnumType();
    }

    /**
     * Create an instance of {@link AttributeType }
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Group }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "group")
    public JAXBElement<Group> createGroup(Group value) {
        return new JAXBElement<Group>(_Group_QNAME, Group.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamespaceType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "namespace")
    public JAXBElement<NamespaceType> createNamespace(NamespaceType value) {
        return new JAXBElement<NamespaceType>(_Namespace_QNAME, NamespaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "endpoint")
    public JAXBElement<EndpointType> createEndpoint(EndpointType value) {
        return new JAXBElement<EndpointType>(_Endpoint_QNAME, EndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectorType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "connector")
    public JAXBElement<ConnectorType> createConnector(ConnectorType value) {
        return new JAXBElement<ConnectorType>(_Connector_QNAME, ConnectorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Attributes }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "attributes")
    public JAXBElement<Attributes> createAttributes(Attributes value) {
        return new JAXBElement<Attributes>(_Attributes_QNAME, Attributes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeCategory }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "attribute-category")
    public JAXBElement<AttributeCategory> createAttributeCategory(AttributeCategory value) {
        return new JAXBElement<AttributeCategory>(_AttributeCategory_QNAME, AttributeCategory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatternType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "pattern")
    public JAXBElement<PatternType> createPattern(PatternType value) {
        return new JAXBElement<PatternType>(_Pattern_QNAME, PatternType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NestedElementType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "nested")
    public JAXBElement<NestedElementType> createNested(NestedElementType value) {
        return new JAXBElement<NestedElementType>(_Nested_QNAME, NestedElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GlobalType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "global")
    public JAXBElement<GlobalType> createGlobal(GlobalType value) {
        return new JAXBElement<GlobalType>(_Global_QNAME, GlobalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScopeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "scope")
    public JAXBElement<ScopeType> createScope(ScopeType value) {
        return new JAXBElement<ScopeType>(_Scope_QNAME, ScopeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "modeSwitch", scope = Group.class)
    public JAXBElement<ModeType> createGroupModeSwitch(ModeType value) {
        return new JAXBElement<ModeType>(_GroupModeSwitch_QNAME, ModeType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "regexp", scope = Group.class)
    public JAXBElement<AttributeType> createGroupRegexp(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupRegexp_QNAME, AttributeType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Booleantype }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "transientBoolean", scope = Group.class)
    public JAXBElement<Booleantype> createGroupTransientBoolean(Booleantype value) {
        return new JAXBElement<Booleantype>(_GroupTransientBoolean_QNAME, Booleantype.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncodingType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "encoding", scope = Group.class)
    public JAXBElement<EncodingType> createGroupEncoding(EncodingType value) {
        return new JAXBElement<EncodingType>(_GroupEncoding_QNAME, EncodingType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "path", scope = Group.class)
    public JAXBElement<AttributeType> createGroupPath(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupPath_QNAME, AttributeType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Booleantype }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "boolean", scope = Group.class)
    public JAXBElement<Booleantype> createGroupBoolean(Booleantype value) {
        return new JAXBElement<Booleantype>(_GroupBoolean_QNAME, Booleantype.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NestedElementReference }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "childElement", scope = Group.class)
    public JAXBElement<NestedElementReference> createGroupChildElement(NestedElementReference value) {
        return new JAXBElement<NestedElementReference>(_GroupChildElement_QNAME, NestedElementReference.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringAttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "string", scope = Group.class)
    public JAXBElement<StringAttributeType> createGroupString(StringAttributeType value) {
        return new JAXBElement<StringAttributeType>(_GroupString_QNAME, StringAttributeType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "name", scope = Group.class)
    public JAXBElement<AttributeType> createGroupName(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupName_QNAME, AttributeType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "file", scope = Group.class)
    public JAXBElement<AttributeType> createGroupFile(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupFile_QNAME, AttributeType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringAttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "password", scope = Group.class)
    public JAXBElement<StringAttributeType> createGroupPassword(StringAttributeType value) {
        return new JAXBElement<StringAttributeType>(_GroupPassword_QNAME, StringAttributeType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LongType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "long", scope = Group.class)
    public JAXBElement<LongType> createGroupLong(LongType value) {
        return new JAXBElement<LongType>(_GroupLong_QNAME, LongType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UrlType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "url", scope = Group.class)
    public JAXBElement<UrlType> createGroupUrl(UrlType value) {
        return new JAXBElement<UrlType>(_GroupUrl_QNAME, UrlType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "globalRef", scope = Group.class)
    public JAXBElement<NewType> createGroupGlobalRef(NewType value) {
        return new JAXBElement<NewType>(_GroupGlobalRef_QNAME, NewType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnumType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "enum", scope = Group.class)
    public JAXBElement<EnumType> createGroupEnum(EnumType value) {
        return new JAXBElement<EnumType>(_GroupEnum_QNAME, EnumType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "list", scope = Group.class)
    public JAXBElement<AttributeType> createGroupList(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupList_QNAME, AttributeType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "flowRef", scope = Group.class)
    public JAXBElement<FlowRefType> createGroupFlowRef(FlowRefType value) {
        return new JAXBElement<FlowRefType>(_GroupFlowRef_QNAME, FlowRefType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IntegerType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "integer", scope = Group.class)
    public JAXBElement<IntegerType> createGroupInteger(IntegerType value) {
        return new JAXBElement<IntegerType>(_GroupInteger_QNAME, IntegerType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "classname", scope = Group.class)
    public JAXBElement<ClassType> createGroupClassname(ClassType value) {
        return new JAXBElement<ClassType>(_GroupClassname_QNAME, ClassType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExpressionAttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "expression", scope = Group.class)
    public JAXBElement<ExpressionAttributeType> createGroupExpression(ExpressionAttributeType value) {
        return new JAXBElement<ExpressionAttributeType>(_GroupExpression_QNAME, ExpressionAttributeType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "text", scope = Group.class)
    public JAXBElement<TextType> createGroupText(TextType value) {
        return new JAXBElement<TextType>(_GroupText_QNAME, TextType.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatternType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "cloud-connector", scope = NamespaceType.class)
    public JAXBElement<PatternType> createNamespaceTypeCloudConnector(PatternType value) {
        return new JAXBElement<PatternType>(_NamespaceTypeCloudConnector_QNAME, PatternType.class, NamespaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatternType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "filter", scope = NamespaceType.class)
    public JAXBElement<PatternType> createNamespaceTypeFilter(PatternType value) {
        return new JAXBElement<PatternType>(_NamespaceTypeFilter_QNAME, PatternType.class, NamespaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatternType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "transformer", scope = NamespaceType.class)
    public JAXBElement<PatternType> createNamespaceTypeTransformer(PatternType value) {
        return new JAXBElement<PatternType>(_NamespaceTypeTransformer_QNAME, PatternType.class, NamespaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GlobalType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "global-cloud-connector", scope = NamespaceType.class)
    public JAXBElement<GlobalType> createNamespaceTypeGlobalCloudConnector(GlobalType value) {
        return new JAXBElement<GlobalType>(_NamespaceTypeGlobalCloudConnector_QNAME, GlobalType.class, NamespaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatternType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "flow", scope = NamespaceType.class)
    public JAXBElement<PatternType> createNamespaceTypeFlow(PatternType value) {
        return new JAXBElement<PatternType>(_NamespaceTypeFlow_QNAME, PatternType.class, NamespaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GlobalType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "global-transformer", scope = NamespaceType.class)
    public JAXBElement<GlobalType> createNamespaceTypeGlobalTransformer(GlobalType value) {
        return new JAXBElement<GlobalType>(_NamespaceTypeGlobalTransformer_QNAME, GlobalType.class, NamespaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatternType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "component", scope = NamespaceType.class)
    public JAXBElement<PatternType> createNamespaceTypeComponent(PatternType value) {
        return new JAXBElement<PatternType>(_NamespaceTypeComponent_QNAME, PatternType.class, NamespaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GlobalType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "global-endpoint", scope = NamespaceType.class)
    public JAXBElement<GlobalType> createNamespaceTypeGlobalEndpoint(GlobalType value) {
        return new JAXBElement<GlobalType>(_NamespaceTypeGlobalEndpoint_QNAME, GlobalType.class, NamespaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatternType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "router", scope = NamespaceType.class)
    public JAXBElement<PatternType> createNamespaceTypeRouter(PatternType value) {
        return new JAXBElement<PatternType>(_NamespaceTypeRouter_QNAME, PatternType.class, NamespaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GlobalType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "global-filter", scope = NamespaceType.class)
    public JAXBElement<GlobalType> createNamespaceTypeGlobalFilter(GlobalType value) {
        return new JAXBElement<GlobalType>(_NamespaceTypeGlobalFilter_QNAME, GlobalType.class, NamespaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "regexp", scope = NestedElementType.class)
    public JAXBElement<AttributeType> createNestedElementTypeRegexp(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupRegexp_QNAME, AttributeType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Booleantype }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "transientBoolean", scope = NestedElementType.class)
    public JAXBElement<Booleantype> createNestedElementTypeTransientBoolean(Booleantype value) {
        return new JAXBElement<Booleantype>(_GroupTransientBoolean_QNAME, Booleantype.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "path", scope = NestedElementType.class)
    public JAXBElement<AttributeType> createNestedElementTypePath(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupPath_QNAME, AttributeType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "encoding", scope = NestedElementType.class)
    public JAXBElement<AttributeType> createNestedElementTypeEncoding(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupEncoding_QNAME, AttributeType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Booleantype }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "boolean", scope = NestedElementType.class)
    public JAXBElement<Booleantype> createNestedElementTypeBoolean(Booleantype value) {
        return new JAXBElement<Booleantype>(_GroupBoolean_QNAME, Booleantype.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NestedElementReference }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "childElement", scope = NestedElementType.class)
    public JAXBElement<NestedElementReference> createNestedElementTypeChildElement(NestedElementReference value) {
        return new JAXBElement<NestedElementReference>(_GroupChildElement_QNAME, NestedElementReference.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "name", scope = NestedElementType.class)
    public JAXBElement<AttributeType> createNestedElementTypeName(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupName_QNAME, AttributeType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "string", scope = NestedElementType.class)
    public JAXBElement<AttributeType> createNestedElementTypeString(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupString_QNAME, AttributeType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "file", scope = NestedElementType.class)
    public JAXBElement<AttributeType> createNestedElementTypeFile(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupFile_QNAME, AttributeType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringAttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "password", scope = NestedElementType.class)
    public JAXBElement<StringAttributeType> createNestedElementTypePassword(StringAttributeType value) {
        return new JAXBElement<StringAttributeType>(_GroupPassword_QNAME, StringAttributeType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LongType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "long", scope = NestedElementType.class)
    public JAXBElement<LongType> createNestedElementTypeLong(LongType value) {
        return new JAXBElement<LongType>(_GroupLong_QNAME, LongType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "url", scope = NestedElementType.class)
    public JAXBElement<AttributeType> createNestedElementTypeUrl(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupUrl_QNAME, AttributeType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "globalRef", scope = NestedElementType.class)
    public JAXBElement<AttributeType> createNestedElementTypeGlobalRef(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupGlobalRef_QNAME, AttributeType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "list", scope = NestedElementType.class)
    public JAXBElement<AttributeType> createNestedElementTypeList(AttributeType value) {
        return new JAXBElement<AttributeType>(_GroupList_QNAME, AttributeType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnumType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "enum", scope = NestedElementType.class)
    public JAXBElement<EnumType> createNestedElementTypeEnum(EnumType value) {
        return new JAXBElement<EnumType>(_GroupEnum_QNAME, EnumType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IntegerType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "integer", scope = NestedElementType.class)
    public JAXBElement<IntegerType> createNestedElementTypeInteger(IntegerType value) {
        return new JAXBElement<IntegerType>(_GroupInteger_QNAME, IntegerType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "classname", scope = NestedElementType.class)
    public JAXBElement<ClassType> createNestedElementTypeClassname(ClassType value) {
        return new JAXBElement<ClassType>(_GroupClassname_QNAME, ClassType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExpressionAttributeType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "expression", scope = NestedElementType.class)
    public JAXBElement<ExpressionAttributeType> createNestedElementTypeExpression(ExpressionAttributeType value) {
        return new JAXBElement<ExpressionAttributeType>(_GroupExpression_QNAME, ExpressionAttributeType.class, NestedElementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.mulesoft.org/schema/mule/tooling.attributes", name = "text", scope = NestedElementType.class)
    public JAXBElement<TextType> createNestedElementTypeText(TextType value) {
        return new JAXBElement<TextType>(_GroupText_QNAME, TextType.class, NestedElementType.class, value);
    }

}
