/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 10:40:36 AM CDT 
//


package org.mule.devkit.model.studio;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatternType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="PatternType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mulesoft.org/schema/mule/tooling.attributes}AbstractElementType">
 *       &lt;attribute name="causesSplit" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="processesResponse" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="causesJoin" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="xmlname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatternType")
public class PatternType
        extends AbstractElementType {

    @XmlAttribute(name = "causesSplit")
    protected Boolean causesSplit;
    @XmlAttribute(name = "processesResponse")
    protected Boolean processesResponse;
    @XmlAttribute(name = "causesJoin")
    protected Boolean causesJoin;
    @XmlAttribute(name = "xmlname")
    protected String xmlname;
    @XmlAttribute(name = "returnType")
    protected String returnType;

    /**
     * Gets the value of the causesSplit property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public Boolean isCausesSplit() {
        return causesSplit;
    }

    /**
     * Sets the value of the causesSplit property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setCausesSplit(Boolean value) {
        this.causesSplit = value;
    }

    /**
     * Gets the value of the processesResponse property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public Boolean isProcessesResponse() {
        return processesResponse;
    }

    /**
     * Sets the value of the processesResponse property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setProcessesResponse(Boolean value) {
        this.processesResponse = value;
    }

    /**
     * Gets the value of the causesJoin property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public Boolean isCausesJoin() {
        return causesJoin;
    }

    /**
     * Sets the value of the causesJoin property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setCausesJoin(Boolean value) {
        this.causesJoin = value;
    }

    /**
     * Gets the value of the xmlname property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getXmlname() {
        return xmlname;
    }

    /**
     * Sets the value of the xmlname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setXmlname(String value) {
        this.xmlname = value;
    }

    public String getReturnType() {
        return returnType;
    }

    public void setReturnType(String returnType) {
        this.returnType = returnType;
    }
}